// For Authentication
export const LOGIN_POST_REQUEST="lOGIN_POST_REQUEST"
export const LOGIN_POST_SUCCESS="lOGIN_POST_SUCCESS"
export const LOGIN_POST_FAILURE="lOGIN_POST_FAILURE"
export const REGISTER_POST_SUCCESS="REGISTER_POST_REQUEST"