// For Authentication
export const LOGIN_POST_REQUEST = "lOGIN_POST_REQUEST";
export const LOGIN_POST_SUCCESS = "lOGIN_POST_SUCCESS";
export const LOGIN_POST_FAILURE = "lOGIN_POST_FAILURE";
export const REGISTER_POST_SUCCESS = "REGISTER_POST_REQUEST";

export const GET_BOOK_REQUEST = "GET_BOOK_REQUEST";

export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS";

export const GET_BOOK_FAILURE = "GET_BOOK_RFAILURE";

export const POST_BOOK_SUCCESS = "POST_BOOK_REQUEST";

export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
